### ISSUE TITLE
Any more features that you want me to add to this repo?

### ISSUE THREAD

**Issue by cptdanko** [cptdanko/Html5StarterAppWithSwift#2]
So for everyone who has used this repo? is there anything you would like me to add to this? any features that you would like me to add to this XCode started project template?

**Comment by cptdanko** [comment]
Ok, I have thought of something that I can add to this. I will be adding another branch that uses the new WkWebView introduced in iOS8
https://developer.apple.com/library/ios/documentation/WebKit/Reference/WKWebView_Ref/ 
so I have a branch in this project the utilises the new WkWebView features for this project template.

**Comment by cptdanko** [comment]
Once I add the branch, I will be writing a blog post describing the branch similar to the one I wrote about the notifications branch
http://captaindanko.blogspot.com.au/2015/02/local-notifications-in-ios7-compliant.html
and the one I wrote about this repo as a whole,
http://captaindanko.blogspot.com.au/2014/10/xcode-starter-project-with-ionic-html5.html

**Comment by longxianlin** [comment]
expect your WKWebView tutoial!!!!
is it better performance than Cordova view. 
I try create cordova project and copy into my swift project, like this:

  pod 'Cordova'
  pod 'CordovaPlugin-console'
  pod 'CordovaPlugin-device'
  pod 'CordovaPlugin-network-information'

MySwiftProject
   ++MySwiftProject
   ++Html5Apps
       --App1
          ----www
          ...
       ----App2
          ---www
       ....
 ++Controllers
     Html5AppViewController.swift
Pods

``` Html5AppViewController.swift
class Html5AppViewController: CDVViewController {

    override func viewDidLoad() {
        self.wwwFolderName = "/Html5Apps/App1/www"
        self.startPage = "index.html"

        super.viewDidLoad()
        let width = UIScreen.mainScreen().applicationFrame.width
        let height = UIScreen.mainScreen().applicationFrame.height

        self.view.frame = CGRectMake(0, 0, width, height)

    }

```

not working. 
any suggestion?

**Comment by cptdanko** [comment]
@longxianlin yes I will be adding support for WKWebView soon. The only thing that I have plans for right now is adding Html5 based visualization by 15th of this month. If I don't add support for WKWebView by 15th, then you can expect it sometime towards the end of this month.

I am not not sure how to solve your Cordova problem, sorry.

**Comment by longxianlin** [comment]
thanks.
here an reference for u
http://devgirl.org/2014/11/10/boost-your-ios-8-mobile-app-performance-with-wkwebview/

**Comment by cptdanko** [comment]
as the title of the link you sent says "boost your iOS8 mobile app performance with WkWebView". I have known about the advantages of the WkWebView, however the idea of this repo was to provide an Xcode project template for iOS apps that run on iOS7 and above. I intend to support iOS7 for another year at least.

However like I said, I will look into adding another branch in this repo which will use the WkWebView.

**Comment by cptdanko** [comment]
@longxianlin the project is now converted to use Swift2 and it will work without any problems on Xcode 7. I will be adding support for WkWebView once I added Html5 charting example to this. Do you use any Html5 charting libraries? 

I have also added another branch which will have all the Swift 1 code that would work on Xcode 6

**Comment by longxianlin** [comment]
thanks

**Comment by cptdanko** [comment]
The repo has been updated to use the WKWebView now
