### ISSUE TITLE
ViewController.swift:65:39: 'lastPathComponent' is unavailable: Use lastPathComponent on NSURL instead.

### ISSUE THREAD

**Issue by acmuuu** [cptdanko/Html5StarterAppWithSwift#4]
ViewController.swift:65:39: 'lastPathComponent' is unavailable: Use lastPathComponent on NSURL instead.

**Comment by cptdanko** [comment]
change the line

request.URL!.path?.lastPathComponent

to this

request.URL!.lastPathComponent

**Comment by cptdanko** [comment]
I think it is an Xcode 7 issue and all you need to do is change this line
request.URL!.path?.lastPathComponent
to this
request.URL!.lastPathComponent
